"""empty message

Revision ID: 30cea29376d2
Revises: 5aa2d52bbd36
Create Date: 2017-01-16 15:52:40.465382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cea29376d2'
down_revision = '5aa2d52bbd36'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    ### end Alembic commands ###
