"""empty message

Revision ID: c1186007f775
Revises: c6bce068c809
Create Date: 2017-01-05 15:41:29.656187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1186007f775'
down_revision = 'c6bce068c809'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('photo', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'photo')
    ### end Alembic commands ###
